export interface CountryAllowance {
  country: string;
  abbr: string;
  baseEuro: number;
}

/** All countries from the Bulgarian daily-allowance table (source: daily_allowances_bulgaria_en.csv). */
export const DAILY_ALLOWANCES: CountryAllowance[] = [
  // European Union
  { country: "Austria", abbr: "AUT", baseEuro: 56 },
  { country: "Belgium", abbr: "BEL", baseEuro: 56 },
  { country: "Germany", abbr: "GER", baseEuro: 56 },
  { country: "Greece", abbr: "GRE", baseEuro: 43 },
  { country: "Denmark", abbr: "DEN", baseEuro: 56 },
  { country: "Estonia", abbr: "EST", baseEuro: 44 },
  { country: "Ireland", abbr: "IRL", baseEuro: 50 },
  { country: "Spain", abbr: "ESP", baseEuro: 47 },
  { country: "Italy", abbr: "ITA", baseEuro: 54 },
  { country: "Cyprus", abbr: "CYP", baseEuro: 53 },
  { country: "Latvia", abbr: "LAT", baseEuro: 40 },
  { country: "Lithuania", abbr: "LTU", baseEuro: 54 },
  { country: "Luxembourg", abbr: "LUX", baseEuro: 56 },
  { country: "Malta", abbr: "MLT", baseEuro: 46 },
  { country: "Netherlands", abbr: "NED", baseEuro: 56 },
  { country: "Poland", abbr: "POL", baseEuro: 47 },
  { country: "Portugal", abbr: "POR", baseEuro: 46 },
  { country: "Romania", abbr: "ROU", baseEuro: 46 },
  { country: "Slovakia", abbr: "SVK", baseEuro: 39 },
  { country: "Slovenia", abbr: "SLO", baseEuro: 48 },
  { country: "Hungary", abbr: "HUN", baseEuro: 39 },
  { country: "Finland", abbr: "FIN", baseEuro: 56 },
  { country: "France", abbr: "FRA", baseEuro: 56 },
  { country: "Croatia", abbr: "CRO", baseEuro: 41 },
  { country: "Czechia", abbr: "CZE", baseEuro: 47 },
  { country: "Sweden", abbr: "SWE", baseEuro: 56 },
  { country: "Other countries (EU)", abbr: "OC-EU", baseEuro: 56 },
  // Rest of Europe
  { country: "Albania", abbr: "ALB", baseEuro: 39 },
  { country: "Belarus", abbr: "BLR", baseEuro: 39 },
  { country: "Bosnia and Herzegovina", abbr: "BIH", baseEuro: 39 },
  { country: "United Kingdom", abbr: "GBR", baseEuro: 59 },
  { country: "Gibraltar", abbr: "GIB", baseEuro: 59 },
  { country: "Iceland", abbr: "ISL", baseEuro: 59 },
  { country: "Kosovo", abbr: "KOS", baseEuro: 39 },
  { country: "Liechtenstein", abbr: "LIE", baseEuro: 59 },
  { country: "Moldova", abbr: "MDA", baseEuro: 39 },
  { country: "Monaco", abbr: "MON", baseEuro: 56 },
  { country: "Norway", abbr: "NOR", baseEuro: 59 },
  { country: "North Macedonia", abbr: "MKD", baseEuro: 39 },
  { country: "Russia", abbr: "RUS", baseEuro: 39 },
  { country: "San Marino", abbr: "SMR", baseEuro: 59 },
  { country: "Serbia", abbr: "SRB", baseEuro: 39 },
  { country: "Ukraine", abbr: "UKR", baseEuro: 39 },
  { country: "Montenegro", abbr: "MNE", baseEuro: 39 },
  { country: "Switzerland", abbr: "SUI", baseEuro: 87 },
  { country: "Other countries (Europe)", abbr: "OC-EUR", baseEuro: 50 },
  // Asia & Middle East
  { country: "Azerbaijan", abbr: "AZE", baseEuro: 39 },
  { country: "Armenia", abbr: "ARM", baseEuro: 39 },
  { country: "Afghanistan", abbr: "AFG", baseEuro: 39 },
  { country: "Bangladesh", abbr: "BAN", baseEuro: 39 },
  { country: "Vietnam", abbr: "VIE", baseEuro: 39 },
  { country: "Georgia", abbr: "GEO", baseEuro: 39 },
  { country: "Israel", abbr: "ISR", baseEuro: 55 },
  { country: "India", abbr: "IND", baseEuro: 39 },
  { country: "Indonesia", abbr: "INA", baseEuro: 39 },
  { country: "Iraq", abbr: "IRQ", baseEuro: 39 },
  { country: "Iran", abbr: "IRI", baseEuro: 39 },
  { country: "Yemen", abbr: "YEM", baseEuro: 39 },
  { country: "Jordan", abbr: "JOR", baseEuro: 39 },
  { country: "Kazakhstan", abbr: "KAZ", baseEuro: 39 },
  { country: "Kyrgyzstan", abbr: "KGZ", baseEuro: 39 },
  { country: "China", abbr: "CHN", baseEuro: 39 },
  { country: "North Korea", abbr: "PRK", baseEuro: 39 },
  { country: "South Korea", abbr: "KOR", baseEuro: 50 },
  { country: "Kuwait", abbr: "KUW", baseEuro: 55 },
  { country: "Lebanon", abbr: "LBN", baseEuro: 39 },
  { country: "Malaysia", abbr: "MAS", baseEuro: 39 },
  { country: "Mongolia", abbr: "MGL", baseEuro: 39 },
  { country: "United Arab Emirates", abbr: "UAE", baseEuro: 50 },
  { country: "Pakistan", abbr: "PAK", baseEuro: 39 },
  { country: "Saudi Arabia", abbr: "KSA", baseEuro: 50 },
  { country: "Singapore", abbr: "SGP", baseEuro: 50 },
  { country: "Syria", abbr: "SYR", baseEuro: 39 },
  { country: "Tajikistan", abbr: "TJK", baseEuro: 39 },
  { country: "Turkmenistan", abbr: "TKM", baseEuro: 39 },
  { country: "Turkey", abbr: "TUR", baseEuro: 39 },
  { country: "Uzbekistan", abbr: "UZB", baseEuro: 39 },
  { country: "Japan", abbr: "JPN", baseEuro: 59 },
  { country: "Other countries (Asia & Middle East)", abbr: "OC-AME", baseEuro: 42 },
  // Africa
  { country: "Algeria", abbr: "ALG", baseEuro: 42 },
  { country: "Angola", abbr: "ANG", baseEuro: 42 },
  { country: "Ghana", abbr: "GHA", baseEuro: 37 },
  { country: "DR Congo", abbr: "COD", baseEuro: 37 },
  { country: "Egypt", abbr: "EGY", baseEuro: 37 },
  { country: "Ethiopia", abbr: "ETH", baseEuro: 37 },
  { country: "Zimbabwe", abbr: "ZIM", baseEuro: 37 },
  { country: "Kenya", abbr: "KEN", baseEuro: 37 },
  { country: "Cote d'Ivoire", abbr: "CIV", baseEuro: 37 },
  { country: "Libya", abbr: "LBA", baseEuro: 37 },
  { country: "Mali", abbr: "MLI", baseEuro: 37 },
  { country: "Morocco", abbr: "MAR", baseEuro: 36 },
  { country: "Mozambique", abbr: "MOZ", baseEuro: 37 },
  { country: "Nigeria", abbr: "NGA", baseEuro: 37 },
  { country: "Tunisia", abbr: "TUN", baseEuro: 37 },
  { country: "South Africa", abbr: "RSA", baseEuro: 37 },
  { country: "Other countries (Africa)", abbr: "OC-AFR", baseEuro: 37 },
  // North America
  { country: "Canada", abbr: "CAN", baseEuro: 58 },
  { country: "Mexico", abbr: "MEX", baseEuro: 53 },
  { country: "United States", abbr: "USA", baseEuro: 58 },
  { country: "Other countries (North America)", abbr: "OC-NA", baseEuro: 57 },
  // Central & South America
  { country: "Argentina", abbr: "ARG", baseEuro: 39 },
  { country: "Brazil", abbr: "BRA", baseEuro: 39 },
  { country: "Colombia", abbr: "COL", baseEuro: 39 },
  { country: "Cuba", abbr: "CUB", baseEuro: 58 },
  { country: "Nicaragua", abbr: "NCA", baseEuro: 39 },
  { country: "Peru", abbr: "PER", baseEuro: 39 },
  { country: "Chile", abbr: "CHI", baseEuro: 39 },
  { country: "Other countries (Central & South America)", abbr: "OC-CSA", baseEuro: 42 },
  // Oceania
  { country: "Australia", abbr: "AUS", baseEuro: 64 },
  { country: "New Zealand", abbr: "NZL", baseEuro: 53 },
  { country: "Other countries (Oceania)", abbr: "OC-ANZO", baseEuro: 59 },
];
